### ISSUE TITLE
Error in reading hdf5 data from 10X

### ISSUE THREAD

**Issue by Ashduc** [ttgump/scDeepCluster_pytorch#4]
Hi,
I am trying to run scDeepCluster_pytorch on a dataset in the 10X website. 
https://www.10xgenomics.com/resources/datasets/10k-human-pbmcs-3-v3-1-chromium-controller-3-1-high
I downloaded the [Feature / cell matrix HDF5 (raw) file and used the below command
python run_scDeepCluster.py --data_file 10k_PBMC_3p_nextgem_Chromium_Controller_raw_feature_bc_matrix.h5 --n_clusters 0
I get the below error message
Can you provide any helpful suggestions to resolve this issue? (FYI: it runs perfectly with the example dataset, 10X_PBMC_select_2100)

Thanks 
Traceback (most recent call last):
  File "~\scDeepCluster_pytorch-main\run_scDeepCluster.py", line 65, in <module>
    x = np.array(data_mat['X'])
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "~\site-packages\h5py\_hl\group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'X' doesn't exist)"

**Comment by ttgump** [comment]
As you can see the error message, it says "object 'X' doesn't exist". The h5 files used for scDeepCluster contain a cell by gene matrix, which is named as "X". The "Y" matrix is optional which stores the true labels. If you want to see the detail, you can open the sample h5 file I uploaded to see the format.

**Comment by Ashduc** [comment]
@ttgump I changed the input format as you suggested.
However I get a different error now
(scdeep) ad:~/Downloads/scDeepCluster_pytorch-main$ python3 run_scDeepCluster.py --data_file gene_matrix_pbmc3k.h5 --n_clus
ters 0
### Autoencoder: Successfully preprocessed 13714 genes and 2638 cells.
Traceback (most recent call last):
  File "~/Downloads/scDeepCluster_pytorch-main/run_scDeepCluster.py", line 88, in <module>
    adata = normalize(adata,
  File "~/Downloads/scDeepCluster_pytorch-main/preprocess.py", line 100, in normalize
    sc.pp.normalize_per_cell(adata)
  File "~/.local/lib/python3.10/site-packages/scanpy/preprocessing/_simple.py", line 527, in normalize_per_cell
    normalize_per_cell(adata.X, counts_per_cell_after, counts_per_cell)
  File "~/.local/lib/python3.10/site-packages/scanpy/preprocessing/_simple.py", line 562, in normalize_per_cell
    counts_per_cell /= counts_per_cell_after

**Comment by ttgump** [comment]
> @ttgump I changed the input format as you suggested. However I get a different error now (scdeep) ad:~/Downloads/scDeepCluster_pytorch-main$ python3 run_scDeepCluster.py --data_file gene_matrix_pbmc3k.h5 --n_clus ters 0
> 
> ### Autoencoder: Successfully preprocessed 13714 genes and 2638 cells.
> Traceback (most recent call last): File "~/Downloads/scDeepCluster_pytorch-main/run_scDeepCluster.py", line 88, in adata = normalize(adata, File "~/Downloads/scDeepCluster_pytorch-main/preprocess.py", line 100, in normalize sc.pp.normalize_per_cell(adata) File "~/.local/lib/python3.10/site-packages/scanpy/preprocessing/_simple.py", line 527, in normalize_per_cell normalize_per_cell(adata.X, counts_per_cell_after, counts_per_cell) File "~/.local/lib/python3.10/site-packages/scanpy/preprocessing/_simple.py", line 562, in normalize_per_cell counts_per_cell /= counts_per_cell_after

Could you provide the complete error message? I didn't see any error in your post.
