### ISSUE TITLE
Louvain clustering exception

### ISSUE THREAD

**Issue by renjiaxu** [ttgump/scDeepCluster_pytorch#6]
Thank you very much for your work!
When I reach the Louvain clustering at line 137, I encounter an issue, and the error message is as follows:

``` python
Traceback (most recent call last): 
  File "/root/autodl-tmp/project/remote_/scDeepCluster_pytorch/run_scDeepCluster.py", line 160, in <module>
    sc.tl.louvain(adata_latent, resolution=args.resolution)
  File "/root/miniconda3/lib/python3.8/site-packages/scanpy/tools/_louvain.py", line 151, in louvain
    part = louvain.find_partition(
  File "/root/miniconda3/lib/python3.8/site-packages/louvain/functions.py", line 68, in find_partition
    partition = partition_type(graph,
  File "/root/miniconda3/lib/python3.8/site-packages/louvain/VertexPartition.py", line 769, in __init__
    self._partition = _c_louvain._new_RBConfigurationVertexPartition(pygraph_t,
BaseException: Could not construct partition: vector::_M_default_append

Process finished with exit code 1
```

Could you please tell me how to solve this problem? Thank you very much!

**Comment by ttgump** [comment]
It seems the issue of scanpy, see the discussion in this link: [https://github.com/scverse/scanpy/issues/2341](https://github.com/scverse/scanpy/issues/2341)
